import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import { TemplateEngine } from "./template-engine.js";

export interface AgentProfile {
  name: string;
  role: string;
  phase: string;
  responsibilities: string[];
  inputs: string[];
  outputs: string[];
  promptTemplates: string[];
}

export interface PipelineStepResult {
  agentName: string;
  inputArtifacts: Record<string, string>;
  outputArtifacts: Record<string, string>;
  log: string[];
}

export class AgentRuntime {
  private profiles: Record<string, AgentProfile> = {};

  constructor(private rootDir: string) {
    this.initializeAgentProfiles();
  }

  private initializeAgentProfiles() {
    // Define the profiles representing the agents/ catalog matching schemas/agent.schema.json
    const agentsList = [
      {
        name: "Planner",
        role: "Planejar tarefas e projetos",
        phase: "P",
        responsibilities: ["Criar plano de desenvolvimento", "Decompor em tarefas", "Estimar esforço"],
        inputs: ["Requisitos do usuário"],
        outputs: ["Plano de desenvolvimento", "Lista de tarefas"],
        promptTemplates: ["specification.md"]
      },
      {
        name: "Architect",
        role: "Tomar decisões de arquitetura e design",
        phase: "R",
        responsibilities: ["Criar ADRs", "Desenhar diagramas", "Especificar interfaces"],
        inputs: ["Plano de desenvolvimento"],
        outputs: ["ADR", "Especificações de design"],
        promptTemplates: ["architecture.md"]
      },
      {
        name: "Developer",
        role: "Implementar código seguindo padrões",
        phase: "E",
        responsibilities: ["Escrever código limpo", "Escrever testes unitários", "Seguir contratos"],
        inputs: ["ADR", "Especificações de design"],
        outputs: ["Código", "Testes unitários"],
        promptTemplates: ["debugging.md"]
      },
      {
        name: "Reviewer",
        role: "Revisar código e qualidade",
        phase: "V",
        responsibilities: ["Verificar standards", "Identificar vulnerabilidades", "Recomendar melhorias"],
        inputs: ["Código", "Testes unitários"],
        outputs: ["Relatório de revisão"],
        promptTemplates: ["code-review.md"]
      },
      {
        name: "QA",
        role: "Garantir qualidade através de testes",
        phase: "V",
        responsibilities: ["Executar testes", "Verificar cobertura", "Validar cenários"],
        inputs: ["Código", "Relatório de revisão"],
        outputs: ["Plano de testes", "Relatório de cobertura"],
        promptTemplates: ["testing.md"]
      },
      {
        name: "DevOps",
        role: "Automação, CI/CD e infraestrutura",
        phase: "C",
        responsibilities: ["Configurar pipelines", "Garantir automação", "Realizar deploy"],
        inputs: ["Código", "Relatório de cobertura"],
        outputs: ["Configuração CI/CD", "Log de deploy"],
        promptTemplates: ["automation.md"]
      },
      {
        name: "Documentation",
        role: "Criar e manter documentação do projeto",
        phase: "all",
        responsibilities: ["Gerar README", "Documentar APIs", "Manter guias"],
        inputs: ["Código", "Log de deploy"],
        outputs: ["README", "Referência de API"],
        promptTemplates: ["documentation.md"]
      }
    ];

    agentsList.forEach(a => {
      this.profiles[a.name.toLowerCase()] = a;
    });
  }

  public getAgent(name: string): AgentProfile | undefined {
    return this.profiles[name.toLowerCase()];
  }

  /**
   * Runs a single agent phase, pre-populating context and logging outputs.
   */
  public runAgent(
    agentName: string,
    inputs: Record<string, string>,
    vars: Record<string, string> = {}
  ): PipelineStepResult {
    const agent = this.getAgent(agentName);
    if (!agent) {
      throw new Error(`Agent ${agentName} not found in catalog.`);
    }

    const log: string[] = [];
    log.push(`🤖 Starting Agent: ${agent.name}`);
    log.push(`Role: ${agent.role}`);
    log.push(`Inputs received: ${Object.keys(inputs).join(", ")}`);

    // Handoff verification
    agent.inputs.forEach(req => {
      if (!inputs[req]) {
        log.push(`⚠️ Warning: Expected input "${req}" was not provided.`);
      }
    });

    // Simulate agent processing and output creation
    const outputArtifacts: Record<string, string> = {};
    agent.outputs.forEach(out => {
      // Simulate generating output artifact based on templates or inputs
      const content = `// Generated by ${agent.name} Agent\n// Based on input: ${Object.values(inputs).join(" | ")}\n\n// Content:\n`;
      outputArtifacts[out] = content;
      log.push(`📦 Created output artifact: "${out}"`);
    });

    log.push(`✅ Agent ${agent.name} execution finished.`);

    return {
      agentName: agent.name,
      inputArtifacts: inputs,
      outputArtifacts,
      log
    };
  }
}

export class Orchestrator {
  private runtime: AgentRuntime;

  constructor(private rootDir: string) {
    this.runtime = new AgentRuntime(rootDir);
  }

  /**
   * Executes the full pipeline sequentially:
   * Planner -> Architect -> Developer -> Reviewer -> QA -> DevOps -> Documentation
   */
  public async executePipeline(initialRequirements: string): Promise<PipelineStepResult[]> {
    const results: PipelineStepResult[] = [];
    const executionLogsDir = join(this.rootDir, ".context/runtime/workflows");
    mkdirSync(executionLogsDir, { recursive: true });

    let currentArtifacts: Record<string, string> = {
      "Requisitos do usuário": initialRequirements
    };

    // 1. Planner
    const plannerResult = this.runtime.runAgent("Planner", {
      "Requisitos do usuário": currentArtifacts["Requisitos do usuário"]
    });
    results.push(plannerResult);
    currentArtifacts = { ...currentArtifacts, ...plannerResult.outputArtifacts };

    // 2. Architect
    const architectResult = this.runtime.runAgent("Architect", {
      "Plano de desenvolvimento": currentArtifacts["Plano de desenvolvimento"] || ""
    });
    results.push(architectResult);
    currentArtifacts = { ...currentArtifacts, ...architectResult.outputArtifacts };

    // 3. Developer
    const developerResult = this.runtime.runAgent("Developer", {
      "ADR": currentArtifacts["ADR"] || "",
      "Especificações de design": currentArtifacts["Especificações de design"] || ""
    });
    results.push(developerResult);
    currentArtifacts = { ...currentArtifacts, ...developerResult.outputArtifacts };

    // 4. Reviewer
    const reviewerResult = this.runtime.runAgent("Reviewer", {
      "Código": currentArtifacts["Código"] || "",
      "Testes unitários": currentArtifacts["Testes unitários"] || ""
    });
    results.push(reviewerResult);
    currentArtifacts = { ...currentArtifacts, ...reviewerResult.outputArtifacts };

    // 5. QA
    const qaResult = this.runtime.runAgent("QA", {
      "Código": currentArtifacts["Código"] || "",
      "Relatório de revisão": currentArtifacts["Relatório de revisão"] || ""
    });
    results.push(qaResult);
    currentArtifacts = { ...currentArtifacts, ...qaResult.outputArtifacts };

    // 6. DevOps
    const devopsResult = this.runtime.runAgent("DevOps", {
      "Código": currentArtifacts["Código"] || "",
      "Relatório de cobertura": currentArtifacts["Relatório de cobertura"] || ""
    });
    results.push(devopsResult);
    currentArtifacts = { ...currentArtifacts, ...devopsResult.outputArtifacts };

    // 7. Documentation
    const docResult = this.runtime.runAgent("Documentation", {
      "Código": currentArtifacts["Código"] || "",
      "Log de deploy": currentArtifacts["Log de deploy"] || ""
    });
    results.push(docResult);
    currentArtifacts = { ...currentArtifacts, ...docResult.outputArtifacts };

    // Save final report to runtime logs
    const reportPath = join(executionLogsDir, `pipeline-execution-${Date.now()}.json`);
    writeFileSync(reportPath, JSON.stringify(results, null, 2), "utf-8");

    return results;
  }
}
